# 需要扫描的物理目录（示例，请按实际环境修改）
scan_paths:
  - "D:/音乐"
  - "D:/MyLife"


skip_paths:
  - "D:/MyLife/flomo*"
  - "D:/MyLife/QQ空间备份_1586470758"

# 缩略图配置
thumbnails:
  enabled: true
  size: [400, 400]

# 数据库路径
database:
  path: "data/mylife.db"
