Douban:
#  示例 123456789
  user: ""

Grcores:
  cookie: ""

Flomo:
# 示例 r'data\\flomo\\我的笔记.html'
  file_path: ""
  file_name: ""
  authorization: ""
#authorization签名和cookie都是用户认证，
#复制 Cookie：需要先解析 Cookie 中的 Token，再构造Authorization头（或服务器直接从 Cookie 中取 Token）；
#直接复制Authorization：可直接使用，更便捷。

# 找 https://flomoapp.com/api/v1/user/me

#小米运动的csv表存放目录
MiSmartBand5:
  path: "data/Manual_Import_Data/目录名"

#解压路径
Decompress:
  path: "data/zip"

Flyme:
  cookie: ""
  images_path: "data/FlymeImages"
Du:
  cookie: ""
Weread:
  cookie: ""
Zhangyue:
  cookie: ""
Qianji:
  cookie: ""


# 需要扫描的物理目录（示例，请按实际环境修改）
scan_paths:
  - "D:/音乐"
  - "D:/影音"

# 跳过路径 *模糊匹配
skip_paths:
  - "D:/音乐/海阔*"
  - "D:/影音/学习资料"

# 缩略图配置
thumbnails:
  enabled: true
  size: [400, 400]
  path: "data/thumbnails"

MYSQL:
  host: ""
  user: ""
  password: ""
  database: ""

# SQLite数据库保存路径
SQLite:
  path: "data/SQLite.db"

Data_End: "data/Data_End"
Data_Star: "data/Data_Star"